### ISSUE TITLE
KRE Policy Ideas

### ISSUE THREAD

**Issue by kikengineering** [kinecosystem/rewards-engine#58] opened 2020-03-20 18:04 UTC
We are looking to start a bit of a discussion and get some input on a few KRE policy ideas we are working on. It would be great if we could get some feedback before we put in more formal proposals (@asparagusm I know you were interested)

The first is a general approach on how and when the KRE should be changed:

_Central banks like the Bank of Canada and the U.S. Federal Reserve System have adopted preset dates for interest rate changes. It is believed that these preset dates lead to better monetary policy. The KRE similarly, should adopt a preset cadence for algorithmic changes. This will allow developers to feel more confident in their application design decisions.

We propose the following dates for KRE updates (first Monday of April, July and October and December):

April 6, 2020 - Q2 2020 Updates
July 6, 2020 - Q3 2020 Updates
October 5, 2020 - Q4 2020 Updates
December 7, 2020 - Q1 2021 Updates and any larger changes to the KRE for 2021

In addition, the Kin Foundation should reserve the right to make changes to the KRE as necessary in between these dates. These changes should be limited to: closing loopholes that go against the spirit of the KRE, correcting other small errors with minimal impact, and fixing larger issues in the case of emergency._

The second is changing the enforcement strategy for KRE violations. This would be a change to the valid transaction guidelines, replacing SECTION C:

_**SECTION C - PROCESS FOR HANDLING VIOLATIONS**

10. **Reporting a breach**

10.1 Breaches can be reported by anyone through Github: https://github.com/kinecosystem/rewards-engine/issues

(a) the title of the report must contain “KRE Violation” as well as the application’s name

(b) please provide the specific rule that was violated as well as reasonable proof of said violation.

10. **Discussion of violation**

10.1. If we reasonably believe that your Application may have been in breach of these KRE Transaction Guidelines:

(a) we will provide notice to you.  

(b) we will exclude your Application from receiving any payout from the KRE until either the Kin Community Council or the Kin Foundation deems your app is not in violation of these guidelines. You will be paid retroactively for weeks deemed to not be in violation of these guidelines at that time.

(c) within one week of the next KRE payment after the report of the violation on GitHub, the Kin Community Council will examine the use case and decide whether or not the application is in violation. If the application is deemed to be in violation, the topic will be discussed by the Kin Foundation at their next meeting. The Kin Foundation will make the final decision on the breach in question.

11. **Developer deemed to be in violation**

11.1. If we reasonably believe that your Application is in breach of these KRE Transaction Guidelines:

(a) we will provide notice to you.  We may additionally provide steps you need to take to remedy the breach however we are not obliged to do so; and

(b) we will exclude your Application from receiving any payout from the KRE from the date the violation began (or the last date paid by the KRE, whichever is later) until the violation has been remedied.  If your Application is deemed to be in violation, the payout that would have been paid to you will instead be added to the KRE Carryover pool for use in the remainder of 2020.

(c) in the case of minor offences, the Kin Foundation reserves the right to pay all or part of the KRE payouts to the offending applicant during the time of the violation.

11.2  Repeated or an egregious breach of these KRE Transaction Guidelines may result in your temporary or permanent ban from the KRE.  

11.3  Any temporary ban may be instated, lifted or reinstated at our sole discretion and subject to any conditions we see fit.  

12. **Remedying a breach**

If you have breached these KRE Transaction Guidelines:

12.1  we may permit you to remedy the breach where it is capable of remedy by providing an updated version of the Application in each app store it is available evidencing that the Application is no longer in breach of these KRE Transaction Guidelines, however we are not obliged to consider remedial action;

12.2  any payouts from the KRE that the Application may have received during the period the Application was excluded from payouts will not be re-credited._

**Comment by asparagusm** [comment] 2020-03-22 21:30
**SECTION C - PROCESS FOR HANDLING VIOLATIONS**

**10. Reporting a breach**

A breach of these KRE Transaction Guidelines can be reported by creating a new issue on Github: https://github.com/kinecosystem/rewards-engine/issues (a **"Report"**).   The title of the report must contain "KRE Violation" as well as the name of the Application.   In the report, please provide the specific rule(s) that was breached along with evidence.

**11. Decision making process**

11.1. If we reasonably believe that your Application breached these KRE Transaction Guidelines or that there is a case to answer in the Report:

(a) we will provide notice to you; and

(b) we may withhold all payments your Application is due to receive from the KRE until a final decision is made. 

11.2   Within 7 days from the date the Report was posted,  the Kin Community Council will review the Report and the Application and determine whether the relevant breach of these KRE Transaction Guidelines is substantiated:

(a) if the breach is substantiated:  the matter will be referred to the Kin Foundation for a final decision;

(b) if the breach is not substantiated:   the Report will be closed.  Any payments that were withheld from the Application will be released in full.

11.3   No delay in making a decision, or any Application remedying the breach in the intervening period will act as a waiver or impede the decision making process. 

**12. Developer is in violation**

12.1. If we have determined that your Application has breached the KRE Transaction Guidelines:

(a) we will provide notice to you;

(b) your Application will be suspended from receiving any payment from the KRE (if we are already withholding your payments, you will be deemed to be suspended from the date we began withholding these payments);

(c) we may additionally provide steps you need to take to remedy the breach however we are not obliged to give you the option to remedy the breach. 

12.2  Any payments that would have been paid to you during the period of the suspension will instead be added to the KRE Carryover pool for use in the remainder of the current calendar year. 
**[[** If we have given you the option to remedy the breach and you have done so to our satisfaction, we may still pay all or part of these payments to you however this strictly at our discretion. **]]** [to review against CL 12.3 below].

12.3 Repeated or a serious breach of these KRE Transaction Guidelines may result in your temporary or permanent ban from the KRE.

12.4 Any temporary ban or suspension may be instated, lifted or reinstated at our sole discretion and subject to any conditions we see fit.

13.  **Remedying a breach**
If you have breached these KRE Transaction Guidelines:

13.1 we may permit you to remedy the breach where it is capable of remedy by providing an updated version of the Application in each app store it is available evidencing that the Application is no longer in breach of these KRE Transaction Guidelines, however we are not obliged to consider remedial action;

13.2 any payouts from the KRE that the Application may have received during the period the Application was suspended from payouts will not be re-credited._

**Comment by asparagusm** [comment] 2020-03-22 21:33
I think this works a bit better, let me know thoughts

**Comment by kikengineering** [comment] 2020-03-23 14:48
Nice, well-written. Thanks!

One thing you took out was reference to be KF's ability to apply "slap on the wrist punishment" in certain instances. One could imagine a developer having a handful of transactions that were offside, but actually changed their payout very little. Do you think it's worth having a clause like this directly in the policy or safer to remove completely? We could even suggest these slap on the wrist issues are dealt with by the Community Council, not sure if that's the right choice or not but worth thinking through.

**Comment by asparagusm** [comment] 2020-03-23 21:14
Are you referring to this?

>  in the case of minor offences, the Kin Foundation reserves the right to pay all or part of the KRE payouts to the offending applicant during the time of the violation

This sentence was in my view a bit problematic for two reasons,  the first is on the relationship side with the developers, what constitutes a minor offence?  Every developer would claim their offence was minor.   It would lead to a lot confusion in applying the guidelines.  The second,  is this cuts across the mechanics already there.  It is only optional to withhold payments (but in my opinion should always be done while investigating).  If the payments are withheld and the developer remedies their violation, it already has the option to release the payments back to them.

**Comment by kikengineering** [comment] 2020-03-24 19:09
Gotcha, don't think we noticed the end of 13.2 when we read through your improved version. It covers the case we were describing. Our main point was the KF should be allowed the apply slap on the wrist punishments in certain circumstances, not that a developer should be expecting or working to get this outcome.

One fix, the Kin Community Council only meets once every 2 weeks, so we will need to change 7 days -> 14 days in 11.2.

One question: in 11.1 b) do you think it's better to say we *may* withhold your payouts, or just strictly say we will?

**Comment by asparagusm** [comment] 2020-03-24 21:01
Thanks, re-reading this I made some further amends and removed the extra proviso in 13.2.  Slap on the wrist punishment is now dealt with under 12.1(b) and 12.4.  Slight tweak to make the imposition of a suspension optional.   For example,  the KF may decide that despite the proven breach of the guidelines,  the suspension won't be instated subject to the condition of fixing the problem.  That is essentially the slap on the wrist decision as without the suspension being imposed the payments will need to at some point be released back to the developer.  In doing it this way, if the condition is not met, the suspension can still be put in place at a later time without requiring a overwriting a previous 'final' decision. 

There's also only now 3 escalation points: Withhold payments until a decision -> decide to put in place a suspension (subject to any conditions/option to remedy) -> permanent ban.  

My view is that payments should always be withheld during an investigation.  This is because if there are any delays in making the decision or we learn the issue is much more serious then first reported,  we do not lose lots of KIN and $ that we didn't need to.  That could have credibility issues for the KF.

Happy for you to tweak as necessary :)

**Comment by asparagusm** [comment] 2020-03-24 21:03
Now,  the KRE updates calendar - my view is that is a great idea as I saw some developers mentioning they would like to see something like this.   I was wondering what your thoughts were on building this calendar out:  for example,  if you intend to update the KRE on this day,  can you work backwards to decide a date that the proposal must be with the KF for their review, and further backwards for the date draft improvement proposals have to be submitted.  Then you can have a rotating calendar liking all the various arms of this machine so we all know who needs to be doing or reviewing what right now to achieve the relevant date.   What do you think about that?

**Comment by kikengineering** [comment] 2020-04-01 19:06
This is in a PR now (forgot to post when the PR was made):
https://github.com/kinecosystem/rewards-engine/pull/59
Happy to keep discussing.

**Closed** 2021-08-23 23:35 UTC
